/**
 * RosterPack Serie A — CONTENUTO PERSONALE, NON DISTRIBUIRE (GAME_DESIGN §9.2).
 * Profili ispirati alle rose reali a inizio 2026, nomi INVENTATI, fasce di confidenza
 * dichiarate: i profili 'bassa' si rivedono insieme all'utente. Livelli su scala 1-100
 * coerenti col mondo generato (top Serie A ~84-90).
 */

import type { RosterPack } from '../../../src/generation/roster-pack';

/** Milano nerazzurra. */
export const PACK_MILANO_NERAZZURRI: RosterPack = {
  city: 'Milano',
  kitPrimary: '#1f3a68',
  clubName: 'i nerazzurri',
  players: [
    // ---- Portieri
    {
      name: 'Yannis Steinmann',
      age: 37,
      nationality: 'SUI',
      position: 'GK',
      foot: 'R',
      archetype: 'gk-linea',
      level: 84,
      traits: { composure: 0.85, professionalism: 0.85 },
      confidence: 'alta',
    },
    {
      name: 'Josep Mardones',
      age: 25,
      nationality: 'ESP',
      position: 'GK',
      foot: 'R',
      archetype: 'gk-linea',
      level: 78,
      potential: 84,
      confidence: 'media',
    },
    // ---- Difensori
    {
      name: 'Benoît Pasquier',
      age: 30,
      nationality: 'FRA',
      position: 'DF',
      foot: 'R',
      archetype: 'df-impostazione',
      level: 84,
      traits: { professionalism: 0.75 },
      confidence: 'alta',
    },
    {
      name: 'Fabrizio Cerbi',
      age: 38,
      nationality: 'ITA',
      position: 'DF',
      foot: 'L',
      archetype: 'df-marcatore',
      level: 79,
      traits: { professionalism: 0.9, determination: 0.85, leadership: 0.7 },
      confidence: 'alta',
    },
    {
      name: 'Alessio Bastianelli',
      age: 27,
      nationality: 'ITA',
      position: 'DF',
      foot: 'L',
      archetype: 'df-impostazione',
      level: 87,
      standouts: { passing: 88 },
      traits: { composure: 0.8, loyalty: 0.7 },
      trainedHere: true,
      confidence: 'alta',
    },
    {
      name: 'Stefan de Vries',
      age: 34,
      nationality: 'NED',
      position: 'DF',
      foot: 'R',
      archetype: 'df-impostazione',
      level: 81,
      traits: { professionalism: 0.85 },
      confidence: 'alta',
    },
    {
      name: 'Dries Domburg',
      age: 30,
      nationality: 'NED',
      position: 'DF',
      foot: 'R',
      archetype: 'df-fascia-spinta',
      level: 84,
      standouts: { pace: 88, strength: 84 },
      traits: { determination: 0.85, temperament: 0.65 },
      confidence: 'alta',
    },
    {
      name: 'Federico Di Marzio',
      age: 29,
      nationality: 'ITA',
      position: 'DF',
      foot: 'L',
      archetype: 'df-fascia-spinta',
      level: 85,
      standouts: { passing: 86 },
      traits: { loyalty: 0.85 },
      trainedHere: true,
      confidence: 'alta',
    },
    {
      name: 'Carlos Otávio',
      age: 27,
      nationality: 'BRA',
      position: 'DF',
      foot: 'L',
      archetype: 'df-fascia-spinta',
      level: 80,
      confidence: 'media',
    },
    {
      name: 'Matteo Dorini',
      age: 36,
      nationality: 'ITA',
      position: 'DF',
      foot: 'R',
      archetype: 'df-fascia-bloccato',
      level: 76,
      traits: { professionalism: 0.9 },
      confidence: 'media',
    },
    // ---- Centrocampisti
    {
      name: 'Nicola Barigelli',
      age: 29,
      nationality: 'ITA',
      position: 'MF',
      foot: 'R',
      archetype: 'mf-mezzala',
      level: 88,
      standouts: { stamina: 92, workRate: 93 },
      traits: { determination: 0.9, leadership: 0.75, temperament: 0.6 },
      confidence: 'alta',
    },
    {
      name: 'Hakan Çelikkan',
      age: 32,
      nationality: 'TUR',
      position: 'MF',
      foot: 'R',
      archetype: 'mf-regista',
      level: 87,
      standouts: { passing: 92, composure: 88 },
      traits: { composure: 0.85, ambition: 0.7 },
      confidence: 'alta',
    },
    {
      name: 'Aram Petrosyan',
      age: 37,
      nationality: 'ARM',
      position: 'MF',
      foot: 'R',
      archetype: 'mf-mezzala',
      level: 79,
      traits: { professionalism: 0.95, loyalty: 0.7 },
      confidence: 'alta',
    },
    {
      name: 'Davide Frattini',
      age: 27,
      nationality: 'ITA',
      position: 'MF',
      foot: 'R',
      archetype: 'mf-mezzala',
      level: 82,
      standouts: { finishing: 78 },
      traits: { ambition: 0.8, temperament: 0.6 },
      confidence: 'alta',
    },
    {
      name: 'Piotr Zielony',
      age: 32,
      nationality: 'POL',
      position: 'MF',
      foot: 'R',
      archetype: 'mf-trequartista',
      level: 80,
      confidence: 'media',
    },
    {
      name: 'Kristjan Alliu',
      age: 24,
      nationality: 'ALB',
      position: 'MF',
      foot: 'R',
      archetype: 'mf-regista',
      level: 78,
      potential: 84,
      confidence: 'media',
    },
    {
      name: 'Luka Sucin',
      age: 23,
      nationality: 'CRO',
      position: 'MF',
      foot: 'R',
      archetype: 'mf-mezzala',
      level: 79,
      potential: 87,
      confidence: 'bassa',
    },
    // ---- Attaccanti
    {
      name: 'Matías Lezcano',
      age: 29,
      nationality: 'ARG',
      position: 'FW',
      foot: 'R',
      archetype: 'fw-punta-area',
      level: 90,
      standouts: { finishing: 93, workRate: 84 },
      traits: { leadership: 0.9, determination: 0.95, ambition: 0.85 },
      confidence: 'alta',
    },
    {
      name: 'Marcus Thierry',
      age: 29,
      nationality: 'FRA',
      position: 'FW',
      foot: 'R',
      archetype: 'fw-boa',
      level: 86,
      standouts: { pace: 88 },
      traits: { socialita: 0.85 },
      confidence: 'alta',
    },
    {
      name: 'Emanuele Spinetti',
      age: 21,
      nationality: 'ITA',
      position: 'FW',
      foot: 'R',
      archetype: 'fw-boa',
      level: 76,
      potential: 89,
      traits: { professionalism: 0.85, ambition: 0.75 },
      trainedHere: true,
      confidence: 'media',
    },
    {
      name: 'Nikola Zaleski',
      age: 25,
      nationality: 'POL',
      position: 'FW',
      foot: 'L',
      archetype: 'fw-ala-fascia',
      level: 78,
      confidence: 'media',
    },
  ],
};

/** Milano rossonera. */
export const PACK_MILANO_ROSSONERI: RosterPack = {
  city: 'Milano',
  kitPrimary: '#8e2f36',
  clubName: 'i rossoneri',
  players: [
    // ---- Portieri
    {
      name: 'Marcel Magnier',
      age: 31,
      nationality: 'FRA',
      position: 'GK',
      foot: 'R',
      archetype: 'gk-libero',
      level: 86,
      standouts: { oneOnOne: 90 },
      traits: { leadership: 0.85, temperament: 0.6 },
      confidence: 'alta',
    },
    {
      name: 'Lorenzo Terragni',
      age: 24,
      nationality: 'ITA',
      position: 'GK',
      foot: 'R',
      archetype: 'gk-linea',
      level: 74,
      confidence: 'bassa',
    },
    // ---- Difensori
    {
      name: 'Marcus Tomlin',
      age: 28,
      nationality: 'ENG',
      position: 'DF',
      foot: 'R',
      archetype: 'df-marcatore',
      level: 83,
      standouts: { pace: 88 },
      traits: { determination: 0.8 },
      confidence: 'alta',
    },
    {
      name: 'Matteo Gabrielli',
      age: 27,
      nationality: 'ITA',
      position: 'DF',
      foot: 'R',
      archetype: 'df-marcatore',
      level: 80,
      traits: { loyalty: 0.85, professionalism: 0.8 },
      trainedHere: true,
      confidence: 'alta',
    },
    {
      name: 'Stefan Pavicic',
      age: 25,
      nationality: 'SRB',
      position: 'DF',
      foot: 'L',
      archetype: 'df-marcatore',
      level: 82,
      standouts: { strength: 90 },
      traits: { temperament: 0.75, determination: 0.85 },
      confidence: 'alta',
    },
    {
      name: 'Joris Dewulf',
      age: 24,
      nationality: 'BEL',
      position: 'DF',
      foot: 'R',
      archetype: 'df-impostazione',
      level: 79,
      potential: 85,
      confidence: 'media',
    },
    {
      name: 'Álvaro Jimeno',
      age: 21,
      nationality: 'ESP',
      position: 'DF',
      foot: 'R',
      archetype: 'df-fascia-spinta',
      level: 76,
      potential: 85,
      confidence: 'media',
    },
    {
      name: 'Pablo Estigarribia',
      age: 28,
      nationality: 'ECU',
      position: 'DF',
      foot: 'L',
      archetype: 'df-fascia-spinta',
      level: 79,
      confidence: 'media',
    },
    {
      name: 'Davide Bertesini',
      age: 20,
      nationality: 'ITA',
      position: 'DF',
      foot: 'L',
      archetype: 'df-fascia-bloccato',
      level: 73,
      potential: 83,
      trainedHere: true,
      confidence: 'bassa',
    },
    // ---- Centrocampisti
    {
      name: 'Lovre Mandaric',
      age: 40,
      nationality: 'CRO',
      position: 'MF',
      foot: 'R',
      archetype: 'mf-regista',
      level: 84,
      standouts: { passing: 93, decisions: 95, composure: 92, pace: 55 },
      traits: { professionalism: 0.98, leadership: 0.95, composure: 0.95 },
      confidence: 'alta',
    },
    {
      name: 'Adrien Rambert',
      age: 31,
      nationality: 'FRA',
      position: 'MF',
      foot: 'L',
      archetype: 'mf-tuttocampista',
      level: 84,
      standouts: { strength: 86 },
      traits: { ambition: 0.6, temperament: 0.55 },
      confidence: 'alta',
    },
    {
      name: 'Youssouf Fadiga',
      age: 27,
      nationality: 'FRA',
      position: 'MF',
      foot: 'R',
      archetype: 'mf-mediano',
      level: 82,
      confidence: 'alta',
    },
    {
      name: 'Reuben Lofton',
      age: 30,
      nationality: 'ENG',
      position: 'MF',
      foot: 'R',
      archetype: 'mf-mezzala',
      level: 80,
      standouts: { strength: 88, dribbling: 82 },
      confidence: 'media',
    },
    {
      name: 'Samuele Riccardi',
      age: 25,
      nationality: 'ITA',
      position: 'MF',
      foot: 'R',
      archetype: 'mf-regista',
      level: 81,
      potential: 86,
      traits: { professionalism: 0.85 },
      confidence: 'alta',
    },
    {
      name: 'Ardian Jasari',
      age: 23,
      nationality: 'SUI',
      position: 'MF',
      foot: 'R',
      archetype: 'mf-mediano',
      level: 79,
      potential: 86,
      confidence: 'media',
    },
    // ---- Attaccanti
    {
      name: 'Rafael Leandro',
      age: 27,
      nationality: 'POR',
      position: 'FW',
      foot: 'R',
      archetype: 'fw-ala-invertita',
      level: 88,
      standouts: { pace: 95, dribbling: 93, workRate: 62 },
      traits: { consistency: 0.35, socialita: 0.9, ambition: 0.75, divergente: true },
      confidence: 'alta',
    },
    {
      name: 'Chris Pulaski',
      age: 28,
      nationality: 'USA',
      position: 'FW',
      foot: 'R',
      archetype: 'fw-seconda-punta',
      level: 85,
      standouts: { workRate: 88 },
      traits: { professionalism: 0.9, determination: 0.85 },
      confidence: 'alta',
    },
    {
      name: 'Santiago Juárez',
      age: 25,
      nationality: 'MEX',
      position: 'FW',
      foot: 'L',
      archetype: 'fw-punta-area',
      level: 81,
      traits: { determination: 0.8, consistency: 0.45 },
      confidence: 'media',
    },
    {
      name: 'Camille Nakoumé',
      age: 28,
      nationality: 'FRA',
      position: 'FW',
      foot: 'R',
      archetype: 'fw-falso-nove',
      level: 83,
      standouts: { dribbling: 87 },
      confidence: 'media',
    },
    {
      name: 'Samuel Chikwendu',
      age: 27,
      nationality: 'NGA',
      position: 'FW',
      foot: 'L',
      archetype: 'fw-ala-invertita',
      level: 78,
      standouts: { pace: 90 },
      confidence: 'media',
    },
  ],
};
