/**
 * La libreria dei brand sponsor (MODULE_SPONSORS §2): ~200 aziende fittizie in 5 taglie,
 * ispirate al reale con nomi DISTORTI in chiave parodica (mai identici). `nation` (dal
 * pool nazionalità del mondo) abilita la clausola merchandising; `showcase` la clausola
 * vetrina; gli `special` sono scommesse (solo club facoltosi) e benefico (zero soldi).
 */

import type { SponsorSlot } from '../core/types.js';

export type SponsorTier = 'micro' | 'piccola' | 'media' | 'grande' | 'multinazionale';
export type SponsorCharacter = 'esigente' | 'paziente' | 'progetto';

export interface SponsorBrand {
  id: string;
  name: string;
  sector: string;
  tier: SponsorTier;
  /** Nazione (pool del mondo) → clausola merch disponibile. */
  nation?: string;
  slots: readonly SponsorSlot[];
  character: SponsorCharacter;
  special?: 'scommesse' | 'benefico';
  /** Multinazionali esigenti: clausola vetrina (premio su obiettivo centrato). */
  showcase?: boolean;
}

const MAIN: readonly SponsorSlot[] = ['maglia', 'stadio', 'allenamento'];
const KIT: readonly SponsorSlot[] = ['tecnico', 'allenamento'];

let seq = 0;
function b(
  tier: SponsorTier,
  sector: string,
  name: string,
  opts: Partial<Pick<SponsorBrand, 'nation' | 'slots' | 'character' | 'special' | 'showcase'>> = {},
): SponsorBrand {
  return {
    id: `sp-${seq++}`,
    name,
    sector,
    tier,
    nation: opts.nation,
    slots: opts.slots ?? MAIN,
    character: opts.character ?? 'paziente',
    special: opts.special,
    showcase: opts.showcase,
  };
}

export const SPONSOR_BRANDS: readonly SponsorBrand[] = [
  // ══════════ MULTINAZIONALI (i giganti: corteggiano solo i famosi) ══════════
  b('multinazionale', 'compagnia aerea', 'Al-Miraj Airways', {
    character: 'esigente',
    showcase: true,
  }),
  b('multinazionale', 'compagnia aerea', 'Qatarina Airways', {
    character: 'esigente',
    showcase: true,
  }),
  b('multinazionale', 'compagnia aerea', 'Luftanza', { nation: 'GER', character: 'esigente' }),
  b('multinazionale', 'compagnia aerea', 'Aerofrancia', { nation: 'FRA' }),
  b('multinazionale', 'tech', 'Samsonix', { character: 'esigente', showcase: true }),
  b('multinazionale', 'tech', 'Pear Computers', { character: 'esigente', showcase: true }),
  b('multinazionale', 'tech', 'Macrosoft', { character: 'progetto' }),
  b('multinazionale', 'tech', 'Gugola', { character: 'esigente' }),
  b('multinazionale', 'tech', 'Nipponex', { character: 'progetto' }),
  b('multinazionale', 'e-commerce', 'Amazzonia Prime', { character: 'esigente', showcase: true }),
  b('multinazionale', 'e-commerce', 'Alibabbà', { character: 'esigente' }),
  b('multinazionale', 'streaming', 'Netflux', { character: 'esigente' }),
  b('multinazionale', 'streaming', 'Spotifai', { character: 'progetto' }),
  b('multinazionale', 'auto', 'Bavaria Motors', {
    nation: 'GER',
    character: 'esigente',
    showcase: true,
  }),
  b('multinazionale', 'auto', 'Mercadia', { nation: 'GER', character: 'esigente' }),
  b('multinazionale', 'auto', 'Wolfsburg Auto', { nation: 'GER', character: 'progetto' }),
  b('multinazionale', 'auto', 'Toyora', { character: 'progetto' }),
  b('multinazionale', 'auto', 'Hyundong', { character: 'paziente' }),
  b('multinazionale', 'auto', 'Stellantide', { nation: 'ITA', character: 'progetto' }),
  b('multinazionale', 'energia', 'Voltera Energy', { character: 'progetto' }),
  b('multinazionale', 'energia', 'TotalEnergia', { nation: 'FRA' }),
  b('multinazionale', 'petrolio', 'Shellter Oil', { character: 'esigente' }),
  b('multinazionale', 'banca', 'Golden Sax', { character: 'esigente', showcase: true }),
  b('multinazionale', 'banca', 'UniCreditore', { nation: 'ITA', character: 'progetto' }),
  b('multinazionale', 'banca', 'Santanderos', { nation: 'ESP', character: 'progetto' }),
  b('multinazionale', 'assicurazioni', 'Allianza', { nation: 'GER', character: 'progetto' }),
  b('multinazionale', 'assicurazioni', 'Assix', { nation: 'FRA' }),
  b('multinazionale', 'telco', 'Vodafonia', { nation: 'ENG' }),
  b('multinazionale', 'telco', 'Orangia Telecom', { nation: 'FRA' }),
  b('multinazionale', 'bevande', 'CocaLoca', { character: 'esigente', showcase: true }),
  b('multinazionale', 'bevande', 'PepsiCon', { character: 'esigente' }),
  b('multinazionale', 'energy drink', 'RedTaurus', { character: 'esigente', showcase: true }),
  b('multinazionale', 'birra', 'Heinekener', { nation: 'NED', character: 'progetto' }),
  b('multinazionale', 'fast food', "McRonald's", { character: 'paziente' }),
  b('multinazionale', 'fast food', 'Burger Kong', { character: 'paziente' }),
  b('multinazionale', 'caffè', 'Starbax Coffee', { character: 'progetto' }),
  b('multinazionale', 'dolciumi', 'Fantero Dolciumi', { nation: 'ITA', character: 'progetto' }),
  b('multinazionale', 'moda', 'Guccino', { nation: 'ITA', character: 'esigente', showcase: true }),
  b('multinazionale', 'moda', 'Louis Vuittone', { nation: 'FRA', character: 'esigente' }),
  b('multinazionale', 'moda', 'Zarina', { nation: 'ESP' }),
  b('multinazionale', 'orologi', 'Rolexus', { character: 'esigente', showcase: true }),
  b('multinazionale', 'pneumatici', 'Pirellone', { nation: 'ITA', character: 'progetto' }),
  b('multinazionale', 'pneumatici', 'Michelinò', { nation: 'FRA', character: 'progetto' }),
  b('multinazionale', 'kit maker', 'Nikaia', { slots: KIT, character: 'esigente', showcase: true }),
  b('multinazionale', 'kit maker', 'Adelphas', {
    nation: 'GER',
    slots: KIT,
    character: 'esigente',
    showcase: true,
  }),
  b('multinazionale', 'kit maker', 'Pumar', { nation: 'GER', slots: KIT, character: 'progetto' }),
  b('multinazionale', 'scommesse', 'Bet360', { special: 'scommesse', character: 'paziente' }),
  b('multinazionale', 'scommesse', 'BetFaro', { special: 'scommesse', character: 'paziente' }),
  b('multinazionale', 'benefica', 'UNIKID', { special: 'benefico', character: 'paziente' }),
  b('multinazionale', 'benefica', 'WildFund', { special: 'benefico', character: 'paziente' }),

  // ══════════ GRANDI (nazionali affermate) ══════════
  b('grande', 'tv', 'SkyVisione', { character: 'esigente' }),
  b('grande', 'streaming sport', 'DAZZ', { character: 'esigente' }),
  b('grande', 'energia', 'Enia Energia', { nation: 'ITA', character: 'progetto' }),
  b('grande', 'energia', 'Edilume', { nation: 'ITA' }),
  b('grande', 'energia', 'Iberdrolla', { nation: 'ESP' }),
  b('grande', 'retail sport', 'Decathlonia', { nation: 'FRA', character: 'progetto' }),
  b('grande', 'retail sport', 'JB Sports', { nation: 'ENG' }),
  b('grande', 'retail sport', 'Boot Locker', { character: 'paziente' }),
  b('grande', 'assicurazioni', 'Generosa Assicurazioni', { nation: 'ITA', character: 'progetto' }),
  b('grande', 'logistica', 'Poste Prima', { nation: 'ITA', character: 'progetto' }),
  b('grande', 'logistica', 'DHLL Express', { nation: 'GER' }),
  b('grande', 'logistica', 'FedExpress', { character: 'paziente' }),
  b('grande', 'viaggi', 'Bookify Travel', { character: 'esigente' }),
  b('grande', 'viaggi', 'AirBeB', { character: 'paziente' }),
  b('grande', 'compagnia aerea', 'Ryanjet', { character: 'paziente' }),
  b('grande', 'compagnia aerea', 'BreezyJet', { nation: 'ENG' }),
  b('grande', 'compagnia aerea', 'Aeritalia', { nation: 'ITA', character: 'progetto' }),
  b('grande', 'auto', 'Renolt', { nation: 'FRA', character: 'progetto' }),
  b('grande', 'auto', 'Peugeotto', { nation: 'FRA' }),
  b('grande', 'auto', 'Citrouenne', { nation: 'FRA' }),
  b('grande', 'auto', 'Sivilla Motor', { nation: 'ESP' }),
  b('grande', 'auto', 'Audix', { nation: 'GER', character: 'esigente' }),
  b('grande', 'auto', 'Lamborghetti', { nation: 'ITA', character: 'esigente', showcase: true }),
  b('grande', 'supermercati', 'Essequadra', { nation: 'ITA', character: 'progetto' }),
  b('grande', 'supermercati', 'Carrefive', { nation: 'FRA' }),
  b('grande', 'supermercati', 'Lidler', { nation: 'GER', character: 'paziente' }),
  b('grande', 'supermercati', 'Tesoro Market', { nation: 'ENG' }),
  b('grande', 'fintech', 'Bitfinix', { character: 'esigente' }),
  b('grande', 'fintech', 'eTorro', { character: 'esigente' }),
  b('grande', 'gaming', 'GameStation', { character: 'esigente' }),
  b('grande', 'gaming', 'Ybox', { character: 'paziente' }),
  b('grande', 'gaming', 'Epico Games', { character: 'esigente' }),
  b('grande', 'birra', 'Moretta Birra', { nation: 'ITA', character: 'progetto' }),
  b('grande', 'birra', 'Peronza', { nation: 'ITA' }),
  b('grande', 'kit maker', 'Koppa', { nation: 'ITA', slots: KIT, character: 'progetto' }),
  b('grande', 'kit maker', 'Makron', { nation: 'ITA', slots: KIT, character: 'progetto' }),
  b('grande', 'kit maker', 'NeoBalance', { slots: KIT }),
  b('grande', 'kit maker', 'Le Gallo', { nation: 'FRA', slots: KIT }),
  b('grande', 'scommesse', 'ScomMax', {
    nation: 'ITA',
    special: 'scommesse',
    character: 'paziente',
  }),
  b('grande', 'scommesse', 'GoldWin', { special: 'scommesse', character: 'paziente' }),
  b('grande', 'scommesse', 'PlanetBet', { special: 'scommesse', character: 'paziente' }),
  b('grande', 'scommesse', 'WinBet24', { special: 'scommesse', character: 'paziente' }),
  b('grande', 'benefica', 'Save the Future', { special: 'benefico', character: 'paziente' }),
  b('grande', 'benefica', 'Cuore Rosso', {
    nation: 'ITA',
    special: 'benefico',
    character: 'paziente',
  }),
  b('grande', 'benefica', 'Urgency', { special: 'benefico', character: 'paziente' }),

  // ══════════ MEDIE (regionali solide) ══════════
  b('media', 'banca', 'Banca del Borgo', { nation: 'ITA', character: 'progetto' }),
  b('media', 'banca', 'Cassa Adriatica', { nation: 'ITA', character: 'progetto' }),
  b('media', 'banca', 'Midland Counties Bank', { nation: 'ENG', character: 'progetto' }),
  b('media', 'assicurazioni', 'Brumar Assicurazioni', { nation: 'ITA' }),
  b('media', 'acque', 'Levigata Acque', { nation: 'ITA' }),
  b('media', 'acque', 'San Bonifacio Fonti', { nation: 'ITA', character: 'progetto' }),
  b('media', 'caffè', 'Lavazzo Caffè', { nation: 'ITA', character: 'progetto' }),
  b('media', 'caffè', 'Willy Caffè', { nation: 'ITA' }),
  b('media', 'pasta', 'Farilla Pasta', { nation: 'ITA', character: 'progetto' }),
  b('media', 'pasta', 'Del Grano Pasta', { nation: 'ITA' }),
  b('media', 'dolciumi', 'Mulino Blu', { nation: 'ITA', character: 'paziente' }),
  b('media', 'caseificio', 'Galbanetti Formaggi', { nation: 'ITA' }),
  b('media', 'latte', 'Parmalatte', { nation: 'ITA' }),
  b('media', 'salumi', 'Rovagnotti Salumi', { nation: 'ITA' }),
  b('media', 'salumi', 'Bergamotta Salumi', { nation: 'ITA' }),
  b('media', 'vino', 'Cantine Valpolenta', { nation: 'ITA', character: 'progetto' }),
  b('media', 'food', 'Pies & Ale Co.', { nation: 'ENG' }),
  b('media', 'tè', 'Royal Kettle Tea', { nation: 'ENG', character: 'progetto' }),
  b('media', 'edilizia', 'Mattone Forte Edilizia', { nation: 'ITA' }),
  b('media', 'edilizia', 'BuildWell Ltd', { nation: 'ENG' }),
  b('media', 'fitness', 'PalestraViva', { nation: 'ITA', character: 'paziente' }),
  b('media', 'tech', 'Softanova', { character: 'progetto' }),
  b('media', 'tech', 'Datamare', { nation: 'ITA' }),
  b('media', 'energia', 'Solarpiù', { nation: 'ITA', character: 'progetto' }),
  b('media', 'telco', 'Iliadde', { nation: 'FRA', character: 'paziente' }),
  b('media', 'arredo', 'Divanissimi', { nation: 'ITA' }),
  b('media', 'bricolage', 'Bricoforte', { nation: 'ITA' }),
  b('media', 'moto', 'Ducatello Moto', { nation: 'ITA', character: 'esigente' }),
  b('media', 'moto', 'Vespucci Scooter', { nation: 'ITA', character: 'progetto' }),
  b('media', 'farmaceutica', 'Angelucci Farma', { nation: 'ITA' }),
  b('media', 'farmaceutica', 'Menarina Pharma', { nation: 'ITA' }),
  b('media', 'compagnia aerea', 'AeroPo Regional', { nation: 'ITA', character: 'paziente' }),
  b('media', 'crociere', 'Riva Crociere', { nation: 'ITA' }),
  b('media', 'kit maker', 'Erretre', { nation: 'ITA', slots: KIT, character: 'progetto' }),
  b('media', 'kit maker', 'Diadema', { nation: 'ITA', slots: KIT, character: 'progetto' }),
  b('media', 'kit maker', 'Mizuni', { slots: KIT }),
  b('media', 'kit maker', 'Kelmex', { nation: 'ESP', slots: KIT }),
  b('media', 'scommesse', 'SNAP Scommesse', {
    nation: 'ITA',
    special: 'scommesse',
    character: 'paziente',
  }),
  b('media', 'scommesse', 'Eurobetto', { special: 'scommesse', character: 'paziente' }),
  b('media', 'benefica', 'Banco Solidale', {
    nation: 'ITA',
    special: 'benefico',
    character: 'paziente',
  }),

  // ══════════ PICCOLE (provinciali con ambizione) ══════════
  b('piccola', 'supermercati', 'Supermercati Dorini', { nation: 'ITA' }),
  b('piccola', 'caseificio', 'Caseificio Valtorta', { nation: 'ITA', character: 'progetto' }),
  b('piccola', 'olio', 'Oleificio Pugliese', { nation: 'ITA' }),
  b('piccola', 'birrificio', 'Birrificio del Molo', { nation: 'ITA', character: 'progetto' }),
  b('piccola', 'ristorazione', 'Trattoria Prima', { nation: 'ITA' }),
  b('piccola', 'pasticceria', 'Pasticceria Reale', { nation: 'ITA' }),
  b('piccola', 'autoscuola', 'Autoscuola Veloce', { nation: 'ITA' }),
  b('piccola', 'gomme', 'Centro Gomme Rapido', { nation: 'ITA' }),
  b('piccola', 'idraulica', 'Idraulica F.lli Vasca', { nation: 'ITA' }),
  b('piccola', 'elettrodomestici', 'Elettrodomus', { nation: 'ITA' }),
  b('piccola', 'serramenti', 'Serramenti Chiusini', { nation: 'ITA' }),
  b('piccola', 'vernici', 'Vernici Colorama', { nation: 'ITA' }),
  b('piccola', 'agriturismo', 'Agriturismo Le Vigne', { nation: 'ITA', character: 'progetto' }),
  b('piccola', 'molino', 'Molino Petralta', { nation: 'ITA' }),
  b('piccola', 'dolciumi', 'Dolci del Corso', { nation: 'ITA' }),
  b('piccola', 'salumificio', 'Salumificio Brenta', { nation: 'ITA' }),
  b('piccola', 'caffetteria', 'Caffetteria Sport', { nation: 'ITA' }),
  b('piccola', 'gelateria', 'Gelateria Polare', { nation: 'ITA' }),
  b('piccola', 'cartiera', 'Cartiera del Fiume', { nation: 'ITA' }),
  b('piccola', 'marmi', 'Marmi Carrarese', { nation: 'ITA' }),
  b('piccola', 'pub', 'The Red Lion Pub', { nation: 'ENG' }),
  b('piccola', 'ristorazione', 'Sunday Roast Co.', { nation: 'ENG' }),
  b('piccola', 'panificio', 'Bakers of York', { nation: 'ENG', character: 'progetto' }),
  b('piccola', 'birrificio', 'Northern Ales', { nation: 'ENG', character: 'progetto' }),
  b('piccola', 'dolciumi', 'Seaside Rock Candy', { nation: 'ENG' }),
  b('piccola', 'officina', 'Motor Lane Garage', { nation: 'ENG' }),
  b('piccola', 'giardinaggio', 'Green Lawn Mowers', { nation: 'ENG' }),
  b('piccola', 'edilizia', 'Bricks & Sons', { nation: 'ENG' }),
  b('piccola', 'pescheria', 'Harbour Fishery', { nation: 'ENG' }),
  b('piccola', 'sartoria', 'Cobble Street Tailors', { nation: 'ENG' }),
  b('piccola', 'kit maker', 'Aquila Sportswear', {
    nation: 'ITA',
    slots: KIT,
    character: 'progetto',
  }),
  b('piccola', 'kit maker', 'Corsair Athletic', { slots: KIT }),
  b('piccola', 'kit maker', 'Manto Sport', { nation: 'ITA', slots: KIT, character: 'progetto' }),
  b('piccola', 'tipografia', 'Tipografia Moderna', { nation: 'ITA' }),
  b('piccola', 'ottica', 'Ottica Visione', { nation: 'ITA' }),
  b('piccola', 'farmacia', 'Farmacia Centrale', { nation: 'ITA' }),
  b('piccola', 'vivaio', 'Vivai Verdi', { nation: 'ITA' }),
  b('piccola', 'fitness', 'Palestra Olimpia', { nation: 'ITA' }),
  b('piccola', 'ristorazione', 'Ristorante Bella Vista', { nation: 'ITA' }),
  b('piccola', 'benefica', 'Mensa del Sorriso', {
    nation: 'ITA',
    special: 'benefico',
    character: 'paziente',
  }),

  // ══════════ MICRO (il tessuto del quartiere) ══════════
  b('micro', 'bar', 'Bar Sport', { nation: 'ITA' }),
  b('micro', 'street food', 'Kebab King', { nation: 'ITA' }),
  b('micro', 'pizzeria', 'Pizza al Volo', { nation: 'ITA' }),
  b('micro', 'lavanderia', 'Lavanderia Splendor', { nation: 'ITA' }),
  b('micro', 'barbiere', 'Barbiere Figaro', { nation: 'ITA' }),
  b('micro', 'edicola', 'Edicola del Corso', { nation: 'ITA' }),
  b('micro', 'ortofrutta', 'Frutta e Verdura Gino', { nation: 'ITA' }),
  b('micro', 'panificio', 'Panificio Croccante', { nation: 'ITA' }),
  b('micro', 'macelleria', 'Macelleria Nervo', { nation: 'ITA' }),
  b('micro', 'pescheria', 'Pescheria Onda', { nation: 'ITA' }),
  b('micro', 'fiorista', 'Fiorista Petali', { nation: 'ITA' }),
  b('micro', 'tabaccheria', 'Tabaccheria 21', { nation: 'ITA' }),
  b('micro', 'autolavaggio', 'Autolavaggio Blu', { nation: 'ITA' }),
  b('micro', 'cartoleria', 'Cartoleria Prisma', { nation: 'ITA' }),
  b('micro', 'ferramenta', 'Ferramenta Chiodo', { nation: 'ITA' }),
  b('micro', 'enoteca', 'Enoteca del Vicolo', { nation: 'ITA' }),
  b('micro', 'rosticceria', 'Rosticceria Sprint', { nation: 'ITA' }),
  b('micro', 'gommista', 'Gommista Ruota', { nation: 'ITA' }),
  b('micro', 'sartoria', 'Sartoria Ago e Filo', { nation: 'ITA' }),
  b('micro', 'copisteria', 'Copisteria Lampo', { nation: 'ITA' }),
  b('micro', 'chippy', "Joe's Chippy", { nation: 'ENG' }),
  b('micro', 'caffè', 'Corner Cafe', { nation: 'ENG' }),
  b('micro', 'dolciumi', 'Ye Olde Sweets', { nation: 'ENG' }),
  b('micro', 'lavanderia', 'Lucky Laundrette', { nation: 'ENG' }),
  b('micro', 'barbiere', 'Tip Top Barbers', { nation: 'ENG' }),
  b('micro', 'dischi', 'Penny Lane Records', { nation: 'ENG' }),
  b('micro', 'pub', 'Fox & Hound Inn', { nation: 'ENG' }),
  b('micro', 'utensili', 'Iron Bridge Tools', { nation: 'ENG' }),
  b('micro', 'fiorista', 'Daisy Florist', { nation: 'ENG' }),
  b('micro', 'latteria', 'Milkman Dave', { nation: 'ENG' }),
  b('micro', 'fattoria', 'Windy Hill Farm', { nation: 'ENG' }),
  b('micro', 'street food', 'Sunset Chip Van', { nation: 'ENG' }),
  b('micro', 'circolo', 'Circolo Bocciofilo', { nation: 'ITA' }),
  b('micro', 'pasticceria', 'Pasticceria Mimosa', { nation: 'ITA' }),
  b('micro', 'rosticceria', 'Pollo Arrosto Da Ciro', { nation: 'ITA' }),
  b('micro', 'vini', 'Vini Sfusi Ernesto', { nation: 'ITA' }),
  b('micro', 'ciclofficina', 'Officina Pedale', { nation: 'ITA' }),
  b('micro', 'apicoltura', 'Miele di Collina', { nation: 'ITA' }),
  b('micro', 'agrumi', 'Agrumi del Sud', { nation: 'ITA' }),
  b('micro', 'trattoria', 'Trattoria del Passo', { nation: 'ITA' }),
] as const;

export const brandById = (id: string): SponsorBrand | undefined =>
  SPONSOR_BRANDS.find((x) => x.id === id);
